--------------------------------------------------------
--  DDL for Table AAAA
--------------------------------------------------------

  CREATE TABLE "C##LM"."AAAA" 
   (	"고객번호" VARCHAR2(26 BYTE), 
	"성별" VARCHAR2(26 BYTE), 
	"연령대" VARCHAR2(26 BYTE), 
	"거주지역" VARCHAR2(26 BYTE), 
	"구매금액" NUMBER, 
	"거래건수" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
